import {
  Sparkles,
  Wallet,
  CloudSun,
  ShieldCheck,
  Hotel,
  Plane,
  MapPin,
  Siren,
  WifiOff,
  Navigation,
} from 'lucide-react';
import type {
  Destination,
  Feature,
  PricingPlan,
  NavLink,
  TravelStat,
  CountrySafety,
  SafetyAlert,
  Testimonial,
  FAQItem,
  PackingItem,
  TravelTip,
  WeatherDay,
  AIRecommendation,
  QuickAction,
} from '@/types';

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '/' },
  { label: 'Explore', href: '/explore' },
  { label: 'AI Planner', href: '/planner' },
  { label: 'Safety Hub', href: '/safety' },
  { label: 'Travel Tools', href: '/travel-tools' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export const TRAVEL_STATS: TravelStat[] = [
  { label: 'Countries Covered', value: '195', suffix: '+' },
  { label: 'Trips Planned', value: '2.4', suffix: 'M' },
  { label: 'Active Travelers', value: '580', suffix: 'K' },
  { label: 'Safety Alerts Daily', value: '12', suffix: 'K' },
];

export const FEATURES: Feature[] = [
  {
    id: 'ai-planning',
    title: 'AI Trip Planning',
    description: 'Generate personalized multi-day itineraries in seconds with our AI engine.',
    icon: Sparkles,
    color: 'blue',
  },
  {
    id: 'budget-optimizer',
    title: 'Budget Optimizer',
    description: 'Smart cost breakdowns that keep your trip on budget without sacrificing experience.',
    icon: Wallet,
    color: 'emerald',
  },
  {
    id: 'weather-prediction',
    title: 'Weather Prediction',
    description: '14-day forecasts integrated into your itinerary so you pack and plan perfectly.',
    icon: CloudSun,
    color: 'amber',
  },
  {
    id: 'travel-safety',
    title: 'Travel Safety',
    description: 'Real-time safety scores, crime data, and emergency resources for every country.',
    icon: ShieldCheck,
    color: 'red',
  },
  {
    id: 'hotels',
    title: 'Hotel Recommendations',
    description: 'Curated stays matched to your style — from boutique hideaways to luxury resorts.',
    icon: Hotel,
    color: 'purple',
  },
  {
    id: 'flights',
    title: 'Flight Suggestions',
    description: 'Compare routes and prices across airlines, then drop flights straight into your plan.',
    icon: Plane,
    color: 'sky',
  },
  {
    id: 'attractions',
    title: 'Local Attractions',
    description: 'Discover hidden gems and must-see landmarks ranked by millions of travelers.',
    icon: MapPin,
    color: 'rose',
  },
  {
    id: 'emergency',
    title: 'Emergency Assistant',
    description: 'One-tap access to local police, hospitals, and embassies when you need them most.',
    icon: Siren,
    color: 'orange',
  },
  {
    id: 'offline',
    title: 'Offline Access',
    description: 'Download your full itinerary and maps so you are covered even without signal.',
    icon: WifiOff,
    color: 'teal',
  },
  {
    id: 'live-maps',
    title: 'Live Maps',
    description: 'Interactive 3D maps with real-time transit, traffic, and points of interest.',
    icon: Navigation,
    color: 'indigo',
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    image: 'https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.8,
    reviews: 18420,
    budgetPerDay: 180,
    currency: 'EUR',
    bestSeason: 'Apr – Jun',
    description: 'The City of Light blends timeless romance with world-class art, cuisine, and architecture.',
    attractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Montmartre', 'Seine Cruise'],
    coordinates: { lat: 48.8566, lng: 2.3522 },
    color: '#60a5fa',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.9,
    reviews: 24310,
    budgetPerDay: 160,
    currency: 'JPY',
    bestSeason: 'Mar – May',
    description: 'Where neon-lit futurism meets ancient temples — a city of endless discovery.',
    attractions: ['Shibuya Crossing', 'Senso-ji Temple', 'Mt. Fuji Day Trip', 'Tsukiji Market', 'Akihabara'],
    coordinates: { lat: 35.6762, lng: 139.6503 },
    color: '#f472b6',
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    image: 'https://images.pexels.com/photos/1802255/pexels-photo-1802255.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.7,
    reviews: 15890,
    budgetPerDay: 65,
    currency: 'IDR',
    bestSeason: 'Apr – Oct',
    description: 'Tropical paradise with lush rice terraces, sacred temples, and world-class surf.',
    attractions: ['Uluwatu Temple', 'Tegallalang Rice Terrace', 'Ubud Monkey Forest', 'Seminyak Beach', 'Mount Batur'],
    coordinates: { lat: -8.3405, lng: 115.092 },
    color: '#34d399',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    continent: 'Asia',
    image: 'https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.6,
    reviews: 12750,
    budgetPerDay: 220,
    currency: 'AED',
    bestSeason: 'Nov – Mar',
    description: 'A futuristic desert metropolis of record-breaking skyscrapers and luxury experiences.',
    attractions: ['Burj Khalifa', 'Palm Jumeirah', 'Dubai Mall', 'Desert Safari', 'Marina Cruise'],
    coordinates: { lat: 25.2048, lng: 55.2708 },
    color: '#fbbf24',
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    country: 'Switzerland',
    continent: 'Europe',
    image: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.9,
    reviews: 9620,
    budgetPerDay: 240,
    currency: 'CHF',
    bestSeason: 'Jun – Sep',
    description: 'Snow-capped peaks, crystal lakes, and storybook villages in the heart of the Alps.',
    attractions: ['Matterhorn', 'Lake Geneva', 'Jungfrau Railway', 'Lucerne Chapel Bridge', 'Rhine Falls'],
    coordinates: { lat: 46.8182, lng: 8.2275 },
    color: '#22d3ee',
  },
  {
    id: 'newyork',
    name: 'New York',
    country: 'USA',
    continent: 'North America',
    image: 'https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=1200',
    rating: 4.7,
    reviews: 21540,
    budgetPerDay: 280,
    currency: 'USD',
    bestSeason: 'Sep – Nov',
    description: 'The city that never sleeps — iconic skyline, Broadway, and unmatched energy.',
    attractions: ['Statue of Liberty', 'Central Park', 'Times Square', 'Empire State Building', 'Brooklyn Bridge'],
    coordinates: { lat: 40.7128, lng: -74.006 },
    color: '#a78bfa',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'explorer',
    name: 'Explorer',
    price: { monthly: 0, yearly: 0 },
    description: 'Everything you need to plan your first AI-powered trip.',
    features: [
      '3 AI itinerary generations / month',
      'Access to 50 destinations',
      'Basic safety scores',
      'Offline itinerary access',
      'Community support',
    ],
    highlighted: false,
    cta: 'Start Free',
  },
  {
    id: 'voyager',
    name: 'Voyager',
    price: { monthly: 19, yearly: 190 },
    description: 'For frequent travelers who want the full toolkit.',
    features: [
      'Unlimited AI itineraries',
      'All 195 countries unlocked',
      'Real-time safety alerts',
      'Budget optimizer & live maps',
      'Flight & hotel suggestions',
      'Priority support',
    ],
    highlighted: true,
    cta: 'Start 14-Day Trial',
  },
  {
    id: 'elite',
    name: 'Elite',
    price: { monthly: 49, yearly: 490 },
    description: 'Premium experience for power users and digital nomads.',
    features: [
      'Everything in Voyager',
      'Concierge AI assistant',
      'Emergency SOS + 24/7 hotline',
      'Embassy & hospital directory',
      'Custom trip templates',
      'Dedicated travel manager',
    ],
    highlighted: false,
    cta: 'Go Elite',
  },
];

export const COUNTRIES_SAFETY: CountrySafety[] = [
  {
    id: 'france',
    country: 'France',
    code: 'FR',
    flag: '🇫🇷',
    score: 78,
    crimeLevel: 'moderate',
    medicalLevel: 'low',
    politicalStability: 'moderate',
    coordinates: { lat: 46.2276, lng: 2.2137 },
    emergencyNumbers: { police: '17', ambulance: '15', fire: '18' },
    hospitals: [
      { name: 'Hôpital Universitaire Pitié-Salpêtrière', address: '47-83 Bd de l\'Hôpital, Paris', phone: '+33 1 42 16 00 00' },
      { name: 'Hôpital Européen Georges-Pompidou', address: '20 Rue Leblanc, Paris', phone: '+33 1 56 09 20 00' },
    ],
    embassies: [
      { name: 'U.S. Embassy Paris', address: '2 Ave Gabriel, 75008 Paris', phone: '+33 1 43 12 22 22' },
      { name: 'UK Embassy Paris', address: '35 Rue du Faubourg St-Honoré, Paris', phone: '+33 1 44 51 31 00' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines', 'Hepatitis A'],
      insuranceRequired: false,
      notes: 'EHIC cards accepted for EU residents. Pharmacies widely available.',
    },
  },
  {
    id: 'japan',
    country: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    score: 92,
    crimeLevel: 'low',
    medicalLevel: 'low',
    politicalStability: 'low',
    coordinates: { lat: 36.2048, lng: 138.2529 },
    emergencyNumbers: { police: '110', ambulance: '119', fire: '119' },
    hospitals: [
      { name: 'St. Luke\'s International Hospital', address: '9-1 Akashi-cho, Chuo City, Tokyo', phone: '+81 3 3541 5151' },
      { name: 'Tokyo Medical & Surgical Clinic', address: '32 Jingumae, Shibuya City, Tokyo', phone: '+81 3 3436 3028' },
    ],
    embassies: [
      { name: 'U.S. Embassy Tokyo', address: '1-10-5 Akasaka, Minato-ku, Tokyo', phone: '+81 3 3224 5000' },
      { name: 'UK Embassy Tokyo', address: '1 Ichibancho, Chiyoda-ku, Tokyo', phone: '+81 3 5219 9724' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines', 'Japanese encephalitis (rural)'],
      insuranceRequired: true,
      notes: 'Universal healthcare available; carry insurance for non-residents.',
    },
  },
  {
    id: 'indonesia',
    country: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    score: 64,
    crimeLevel: 'moderate',
    medicalLevel: 'moderate',
    politicalStability: 'moderate',
    coordinates: { lat: -0.7893, lng: 113.9213 },
    emergencyNumbers: { police: '110', ambulance: '118', fire: '113' },
    hospitals: [
      { name: 'Sanglah General Hospital', address: 'Jl. Diponegoro, Denpasar, Bali', phone: '+62 361 227911' },
      { name: 'BIMC Hospital Kuta', address: 'Jl. Bypass Ngurah Rai 100X, Kuta, Bali', phone: '+62 361 761263' },
    ],
    embassies: [
      { name: 'U.S. Consulate Bali', address: 'Jl. Hayam Wuruk 188, Denpasar', phone: '+62 361 233 605' },
      { name: 'UK Honorary Consulate Bali', address: 'Jl. Tirta Nadi II, Sanur', phone: '+62 361 289 455' },
    ],
    medicalInfo: {
      vaccinations: ['Hepatitis A', 'Typhoid', 'Routine vaccines'],
      insuranceRequired: true,
      notes: 'Mosquito-borne diseases present. Use repellent. Medical quality varies by island.',
    },
  },
  {
    id: 'uae',
    country: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    score: 88,
    crimeLevel: 'low',
    medicalLevel: 'low',
    politicalStability: 'low',
    coordinates: { lat: 23.4241, lng: 53.8478 },
    emergencyNumbers: { police: '999', ambulance: '998', fire: '997' },
    hospitals: [
      { name: 'Rashid Hospital', address: '315 Umm Hurair Rd, Dubai', phone: '+971 4 219 2000' },
      { name: 'American Hospital Dubai', address: 'Oud Metha Rd, Dubai', phone: '+971 4 336 7777' },
    ],
    embassies: [
      { name: 'U.S. Embassy Abu Dhabi', address: 'Embassy Plaza, Bainunah Street, Abu Dhabi', phone: '+971 2 414 2200' },
      { name: 'UK Embassy Dubai', address: 'Al Seef Rd, Bur Dubai', phone: '+971 4 309 4444' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines'],
      insuranceRequired: true,
      notes: 'High-quality private healthcare. Carry comprehensive insurance.',
    },
  },
  {
    id: 'switzerland-safe',
    country: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    score: 95,
    crimeLevel: 'low',
    medicalLevel: 'low',
    politicalStability: 'low',
    coordinates: { lat: 46.8182, lng: 8.2275 },
    emergencyNumbers: { police: '117', ambulance: '144', fire: '118' },
    hospitals: [
      { name: 'University Hospital Zurich', address: 'Rämistrasse 100, Zurich', phone: '+41 44 255 1111' },
      { name: 'Hôpitaux Universitaires de Genève', address: 'Rue Gabrielle-Perret-Gentil 4, Geneva', phone: '+41 22 372 0111' },
    ],
    embassies: [
      { name: 'U.S. Embassy Bern', address: 'Sulgeneckstrasse 19, Bern', phone: '+41 31 357 7020' },
      { name: 'UK Embassy Bern', address: 'Thunstrasse 50, Bern', phone: '+41 31 359 7700' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines'],
      insuranceRequired: true,
      notes: 'World-class healthcare. EHIC accepted for EU residents.',
    },
  },
  {
    id: 'usa',
    country: 'United States',
    code: 'US',
    flag: '🇺🇸',
    score: 72,
    crimeLevel: 'moderate',
    medicalLevel: 'low',
    politicalStability: 'moderate',
    coordinates: { lat: 37.0902, lng: -95.7129 },
    emergencyNumbers: { police: '911', ambulance: '911', fire: '911' },
    hospitals: [
      { name: 'NewYork-Presbyterian Hospital', address: '622 W 168th St, New York', phone: '+1 212 305 2500' },
      { name: 'Cedars-Sinai Medical Center', address: '8700 Beverly Blvd, Los Angeles', phone: '+1 310 423 3277' },
    ],
    embassies: [
      { name: 'UK Consulate New York', address: '885 Third Ave, New York', phone: '+1 212 745 0200' },
      { name: 'French Consulate New York', address: '934 Fifth Ave, New York', phone: '+1 212 606 3600' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines'],
      insuranceRequired: true,
      notes: 'No universal healthcare. Comprehensive travel insurance strongly recommended.',
    },
  },
  {
    id: 'uk',
    country: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    score: 82,
    crimeLevel: 'moderate',
    medicalLevel: 'low',
    politicalStability: 'low',
    coordinates: { lat: 55.3781, lng: -3.436 },
    emergencyNumbers: { police: '999', ambulance: '999', fire: '999' },
    hospitals: [
      { name: 'St Thomas\' Hospital', address: 'Westminster Bridge Rd, London', phone: '+44 20 7188 7188' },
      { name: 'Royal Free Hospital', address: 'Pond St, London', phone: '+44 20 7794 0500' },
    ],
    embassies: [
      { name: 'U.S. Embassy London', address: '24 Grosvenor Square, London', phone: '+44 20 7499 9000' },
      { name: 'Japanese Embassy London', address: '101-104 Piccadilly, London', phone: '+44 20 7465 6565' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines'],
      insuranceRequired: false,
      notes: 'NHS available for emergencies. EHIC/GHIC accepted for EU residents.',
    },
  },
  {
    id: 'thailand',
    country: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    score: 70,
    crimeLevel: 'moderate',
    medicalLevel: 'moderate',
    politicalStability: 'moderate',
    coordinates: { lat: 15.87, lng: 100.9925 },
    emergencyNumbers: { police: '191', ambulance: '1669', fire: '199' },
    hospitals: [
      { name: 'Bumrungrad International Hospital', address: '33 Sukhumvit 3, Bangkok', phone: '+66 2 066 8888' },
      { name: 'Bangkok Hospital', address: '2 Soi Soonvijai 7, Bangkok', phone: '+66 2 310 3000' },
    ],
    embassies: [
      { name: 'U.S. Embassy Bangkok', address: '120/22 Wireless Rd, Bangkok', phone: '+66 2 205 4000' },
      { name: 'UK Embassy Bangkok', address: '14 Wireless Rd, Bangkok', phone: '+66 2 305 8333' },
    ],
    medicalInfo: {
      vaccinations: ['Hepatitis A', 'Typhoid', 'Routine vaccines'],
      insuranceRequired: true,
      notes: 'Excellent private hospitals in Bangkok. Rural areas have limited care.',
    },
  },
  {
    id: 'australia',
    country: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    score: 87,
    crimeLevel: 'low',
    medicalLevel: 'low',
    politicalStability: 'low',
    coordinates: { lat: -25.2744, lng: 133.7751 },
    emergencyNumbers: { police: '000', ambulance: '000', fire: '000' },
    hospitals: [
      { name: 'Royal Prince Alfred Hospital', address: 'Missenden Rd, Camperdown, Sydney', phone: '+61 2 9515 6111' },
      { name: 'The Royal Melbourne Hospital', address: '300 Grattan St, Parkville, Melbourne', phone: '+61 3 9342 7000' },
    ],
    embassies: [
      { name: 'U.S. Embassy Canberra', address: 'Moonah Pl, Yarralumla, ACT', phone: '+61 2 6214 5600' },
      { name: 'UK High Commission Canberra', address: 'Commonwealth Ave, Yarralumla', phone: '+61 2 6270 6666' },
    ],
    medicalInfo: {
      vaccinations: ['Routine vaccines'],
      insuranceRequired: true,
      notes: 'Medicare available for residents. Reciprocal agreements with some countries.',
    },
  },
  {
    id: 'mexico',
    country: 'Mexico',
    code: 'MX',
    flag: '🇲🇽',
    score: 58,
    crimeLevel: 'high',
    medicalLevel: 'moderate',
    politicalStability: 'moderate',
    coordinates: { lat: 23.6345, lng: -102.5528 },
    emergencyNumbers: { police: '911', ambulance: '911', fire: '911' },
    hospitals: [
      { name: 'Hospital Ángeles Lomas', address: 'Vialidad de la Barranca 61, Huixquilucan', phone: '+52 55 5246 2200' },
      { name: 'Médica Sur', address: 'Puerto de Pirules 150, Mexico City', phone: '+52 55 5424 7200' },
    ],
    embassies: [
      { name: 'U.S. Embassy Mexico City', address: 'Av. Paseo de la Reforma 305', phone: '+52 55 5080 2000' },
      { name: 'UK Embassy Mexico City', address: 'Río Lerma 71, Cuauhtémoc', phone: '+52 55 5242 8500' },
    ],
    medicalInfo: {
      vaccinations: ['Hepatitis A', 'Typhoid', 'Routine vaccines'],
      insuranceRequired: true,
      notes: 'Private hospitals are high quality. Avoid tap water. Some areas have elevated crime.',
    },
  },
];

export const SAFETY_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-1',
    country: 'Japan',
    type: 'weather',
    severity: 'moderate',
    title: 'Typhoon Warning — Okinawa',
    message: 'Typhoon Khanun approaching Okinawa. Expect heavy rainfall and strong winds through Friday.',
    timestamp: '2 hours ago',
  },
  {
    id: 'alert-2',
    country: 'Indonesia',
    type: 'natural-disaster',
    severity: 'high',
    title: 'Volcanic Activity — Mount Merapi',
    message: 'Increased volcanic activity at Mt. Merapi. Exclusion zone expanded to 5km radius.',
    timestamp: '5 hours ago',
  },
  {
    id: 'alert-3',
    country: 'United States',
    type: 'weather',
    severity: 'moderate',
    title: 'Heat Advisory — Southwest States',
    message: 'Excessive heat warning in effect. Temperatures exceeding 110°F in Arizona and Nevada.',
    timestamp: '8 hours ago',
  },
  {
    id: 'alert-4',
    country: 'France',
    type: 'political',
    severity: 'low',
    title: 'Planned Demonstrations — Paris',
    message: 'Labor union marches scheduled for Thursday in central Paris. Expect transit disruptions.',
    timestamp: '12 hours ago',
  },
  {
    id: 'alert-5',
    country: 'Thailand',
    type: 'health',
    severity: 'moderate',
    title: 'Dengue Fever Outbreak — Bangkok',
    message: 'Elevated dengue cases reported. Use insect repellent and wear long sleeves at dusk.',
    timestamp: '1 day ago',
  },
  {
    id: 'alert-6',
    country: 'Mexico',
    type: 'political',
    severity: 'high',
    title: 'Travel Advisory — Certain States',
    message: 'Reconsider travel to specific states due to criminal activity. Check official advisories.',
    timestamp: '1 day ago',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah Mitchell',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'London, UK',
    rating: 5,
    text: 'WandrAI planned my entire 10-day Japan trip in under a minute. The itinerary was spot-on — every restaurant recommendation was incredible.',
    trip: 'Tokyo, Japan',
  },
  {
    id: 't2',
    name: 'David Chen',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'San Francisco, USA',
    rating: 5,
    text: 'The safety hub gave me real-time alerts about a typhoon near Okinawa. I changed my plans and avoided a disaster. This app is a lifesaver.',
    trip: 'Okinawa, Japan',
  },
  {
    id: 't3',
    name: 'Elena Rossi',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Milan, Italy',
    rating: 5,
    text: 'The budget optimizer saved me €400 on my Paris trip. It found free museum days and local cafés I would have never discovered on my own.',
    trip: 'Paris, France',
  },
  {
    id: 't4',
    name: 'James Okoye',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Lagos, Nigeria',
    rating: 5,
    text: 'Planning a family trip to Bali was effortless. The kids loved the activities WandrAI suggested, and the hotel picks were perfect for families.',
    trip: 'Bali, Indonesia',
  },
  {
    id: 't5',
    name: 'Yuki Tanaka',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Osaka, Japan',
    rating: 5,
    text: 'The 3D Earth visualization sold me instantly. But the real magic is the AI — it understood my travel style better than I did.',
    trip: 'Switzerland',
  },
  {
    id: 't6',
    name: 'Maria Santos',
    avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Madrid, Spain',
    rating: 5,
    text: 'I travel for work monthly. WandrAI has cut my planning time from 3 hours to 5 minutes. The offline access feature is genius for long flights.',
    trip: 'Dubai, UAE',
  },
];

export const HOME_FAQ: FAQItem[] = [
  {
    question: 'How does the AI itinerary generation work?',
    answer: 'Our AI analyzes your destination, budget, travel dates, interests, and travel style to create a personalized day-by-day itinerary. It suggests activities, restaurants, and accommodation matched to your preferences, with cost estimates for each day.',
  },
  {
    question: 'Is WandrAI free to use?',
    answer: 'Yes! The Explorer plan is free forever and includes 3 AI itinerary generations per month. For unlimited trips, real-time safety alerts, and advanced features, upgrade to Voyager ($19/mo) or Elite ($49/mo).',
  },
  {
    question: 'Can I use WandrAI offline?',
    answer: 'Absolutely. Once you generate an itinerary, you can download it for offline access. Your full trip plan, maps, and emergency contacts are available even without an internet connection.',
  },
  {
    question: 'How accurate are the safety scores?',
    answer: 'Safety scores are aggregated from official government travel advisories, local crime data, and real-time alerts from our global monitoring network. Scores update daily to reflect changing conditions.',
  },
  {
    question: 'Which countries are supported?',
    answer: 'WandrAI covers all 195 countries with safety data, emergency contacts, and hospital/embassy directories. AI itinerary generation is fully optimized for the top 50 most-visited destinations.',
  },
  {
    question: 'Can I edit the AI-generated itinerary?',
    answer: 'Yes, every itinerary is fully customizable. Swap activities, change restaurants, adjust budgets, or add your own stops. The AI recalculates costs and logistics automatically.',
  },
];

export const PACKING_CHECKLIST: PackingItem[] = [
  {
    category: 'Essentials',
    items: ['Passport & ID', 'Travel insurance documents', 'Credit/debit cards', 'Local currency', 'Phone & charger', 'Universal adapter'],
  },
  {
    category: 'Clothing',
    items: ['Weather-appropriate outfits', 'Comfortable walking shoes', 'Swimwear', 'Light jacket', 'Formal outfit (optional)'],
  },
  {
    category: 'Health',
    items: ['Prescription medications', 'First-aid kit', 'Hand sanitizer', 'Sunscreen SPF 50+', 'Insect repellent', 'Face masks'],
  },
  {
    category: 'Tech',
    items: ['Power bank', 'Headphones', 'Camera & memory cards', 'Laptop/tablet (optional)', 'Travel SIM or eSIM'],
  },
];

export const TRAVEL_TIPS: TravelTip[] = [
  { icon: 'clock', title: 'Arrive Early', description: 'Get to the airport 3 hours before international flights to avoid stress.' },
  { icon: 'wallet', title: 'Notify Your Bank', description: 'Tell your bank about travel dates to prevent card blocks abroad.' },
  { icon: 'phone', title: 'Download Offline Maps', description: 'Save maps for your destination before you leave Wi-Fi.' },
  { icon: 'shield', title: 'Register with Embassy', description: 'Enroll in your country\'s traveler program for safety alerts.' },
  { icon: 'utensils', title: 'Eat Where Locals Eat', description: 'Skip tourist traps — follow the crowds of residents for authentic food.' },
  { icon: 'camera', title: 'Back Up Photos Daily', description: 'Cloud-back up your photos every night so you never lose memories.' },
];

export const WEATHER_DAYS: WeatherDay[] = [
  { day: 'Today', condition: 'Sunny', icon: 'sun', high: 24, low: 15 },
  { day: 'Tomorrow', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 22, low: 14 },
  { day: 'Day 3', condition: 'Cloudy', icon: 'cloud', high: 19, low: 12 },
  { day: 'Day 4', condition: 'Light Rain', icon: 'cloud-rain', high: 17, low: 11 },
  { day: 'Day 5', condition: 'Sunny', icon: 'sun', high: 23, low: 14 },
];

export const AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec1',
    type: 'destination',
    title: 'Visit Kyoto in Autumn',
    description: 'Based on your love of cultural trips, Kyoto in November offers stunning fall foliage with fewer crowds.',
    action: 'Plan This Trip',
    href: '/planner?dest=tokyo',
  },
  {
    id: 'rec2',
    type: 'deal',
    title: 'Flight prices dropping',
    description: 'Flights to Bali are 23% cheaper this month compared to last. Book before prices rise.',
    action: 'View Flights',
    href: '/planner',
  },
  {
    id: 'rec3',
    type: 'tip',
    title: 'Pack lighter for Bali',
    description: 'Tropical climate means you can skip heavy layers. A carry-on is plenty for a 7-day trip.',
    action: 'Get Packing List',
    href: '/planner',
  },
];

export const QUICK_ACTIONS: QuickAction[] = [
  { id: 'qa1', label: 'New Trip', href: '/planner', icon: 'plus' },
  { id: 'qa2', label: 'Safety Check', href: '/safety', icon: 'shield' },
  { id: 'qa3', label: 'Explore', href: '/#destinations', icon: 'compass' },
  { id: 'qa4', label: 'Settings', href: '/dashboard', icon: 'settings' },
];

export const EARTH_TEXTURE_URL =
  'https://unpkg.com/three-globe@2.31.1/example/img/earth-blue-marble.jpg';
export const EARTH_TOPOLOGY_URL =
  'https://unpkg.com/three-globe@2.31.1/example/img/earth-topology.png';
export const EARTH_NIGHT_URL =
  'https://unpkg.com/three-globe@2.31.1/example/img/earth-night.jpg';
