import {
  Plane, Hotel, Utensils, Car, ShoppingBag, Ticket, Package,
  Cloud, CloudRain, Sun, CloudSnow, Wind, MapPin, Calendar,
  DollarSign, Clock, Globe, Zap, Shield, Heart, Users, Compass,
  Camera, Mountain, Waves, UtensilsCrossed, Building2, Phone,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type {
  CountryDetail, VisaInfo, QuizQuestion, EmergencyPhrase,
  CurrencyRate, UnitConversion, ShareOption, NavLink, Expense,
} from '@/types';

export const FEATURE_NAV_LINKS: NavLink[] = [
  { label: 'World Explorer', href: '/explore' },
  { label: 'Expenses', href: '/expenses' },
  { label: 'Packing List', href: '/packing' },
  { label: 'Visa Center', href: '/visa' },
  { label: 'Compare', href: '/compare' },
  { label: 'Travel Quiz', href: '/quiz' },
  { label: 'Travel Tools', href: '/travel-tools' },
  { label: 'Settings', href: '/settings' },
];

export const COUNTRY_DETAILS: CountryDetail[] = [
  {
    id: 'france',
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    capital: 'Paris',
    currency: 'EUR (€)',
    language: 'French',
    timezone: 'CET (UTC+1)',
    safetyScore: 78,
    bestMonths: 'Apr – Jun, Sep – Oct',
    estimatedBudget: 180,
    image: 'https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 46.2276, lng: 2.2137 },
    attractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral', 'Palace of Versailles', 'Mont Saint-Michel'],
    foodRecommendations: ['Croissant', 'Coq au Vin', 'Ratatouille', 'Crème Brûlée', 'French Onion Soup'],
    localTransport: ['Metro', 'RER Train', 'Bus', 'Vélib Bike Share', 'Taxi'],
    emergencyNumbers: { police: '17', ambulance: '15', fire: '18' },
    weather: { condition: 'Partly Cloudy', temp: 18, high: 22, low: 12 },
  },
  {
    id: 'japan',
    name: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    capital: 'Tokyo',
    currency: 'JPY (¥)',
    language: 'Japanese',
    timezone: 'JST (UTC+9)',
    safetyScore: 92,
    bestMonths: 'Mar – May, Oct – Nov',
    estimatedBudget: 160,
    image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 36.2048, lng: 138.2529 },
    attractions: ['Mount Fuji', 'Fushimi Inari Shrine', 'Senso-ji Temple', 'Arashiyama Bamboo Grove', 'Hiroshima Peace Memorial'],
    foodRecommendations: ['Sushi', 'Ramen', 'Tempura', 'Wagyu Beef', 'Matcha Ice Cream'],
    localTransport: ['Shinkansen', 'JR Train', 'Subway', 'Bus', 'Taxi'],
    emergencyNumbers: { police: '110', ambulance: '119', fire: '119' },
    weather: { condition: 'Sunny', temp: 21, high: 25, low: 16 },
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    capital: 'Jakarta',
    currency: 'IDR (Rp)',
    language: 'Indonesian',
    timezone: 'WIB (UTC+7)',
    safetyScore: 64,
    bestMonths: 'Apr – Oct',
    estimatedBudget: 65,
    image: 'https://images.pexels.com/photos/1802255/pexels-photo-1802255.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: -0.7893, lng: 113.9213 },
    attractions: ['Bali Rice Terraces', 'Borobudur Temple', 'Komodo Island', 'Mount Bromo', 'Gili Islands'],
    foodRecommendations: ['Nasi Goreng', 'Satay', 'Rendang', 'Gado-Gado', 'Babi Guling'],
    localTransport: ['Gojek/Grab', 'Bemo Minivan', 'Ferry', 'Scooter Rental', 'Taxi'],
    emergencyNumbers: { police: '110', ambulance: '118', fire: '113' },
    weather: { condition: 'Sunny', temp: 30, high: 33, low: 25 },
  },
  {
    id: 'uae',
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    capital: 'Abu Dhabi',
    currency: 'AED (د.إ)',
    language: 'Arabic',
    timezone: 'GST (UTC+4)',
    safetyScore: 88,
    bestMonths: 'Nov – Mar',
    estimatedBudget: 220,
    image: 'https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 23.4241, lng: 53.8478 },
    attractions: ['Burj Khalifa', 'Palm Jumeirah', 'Sheikh Zayed Mosque', 'Dubai Fountain', 'Desert Safari'],
    foodRecommendations: ['Shawarma', 'Machboos', 'Luqaimat', 'Harees', 'Karak Tea'],
    localTransport: ['Dubai Metro', 'Abu Dhabi Bus', 'Taxi', 'Ride-Hailing', 'Water Taxi'],
    emergencyNumbers: { police: '999', ambulance: '998', fire: '997' },
    weather: { condition: 'Sunny', temp: 35, high: 40, low: 28 },
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    capital: 'Bern',
    currency: 'CHF (Fr)',
    language: 'German, French, Italian',
    timezone: 'CET (UTC+1)',
    safetyScore: 95,
    bestMonths: 'Jun – Sep, Dec – Feb',
    estimatedBudget: 240,
    image: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 46.8182, lng: 8.2275 },
    attractions: ['Matterhorn', 'Lake Geneva', 'Jungfrau Railway', 'Château de Chillon', 'Rhine Falls'],
    foodRecommendations: ['Fondue', 'Raclette', 'Rösti', 'Swiss Chocolate', 'Zürcher Geschnetzeltes'],
    localTransport: ['SBB Train', 'PostBus', 'Cable Car', 'Boat', 'Tram'],
    emergencyNumbers: { police: '117', ambulance: '144', fire: '118' },
    weather: { condition: 'Cloudy', temp: 14, high: 18, low: 8 },
  },
  {
    id: 'usa',
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    capital: 'Washington, D.C.',
    currency: 'USD ($)',
    language: 'English',
    timezone: 'Multiple (EST to PST)',
    safetyScore: 72,
    bestMonths: 'Apr – Jun, Sep – Nov',
    estimatedBudget: 280,
    image: 'https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 37.0902, lng: -95.7129 },
    attractions: ['Statue of Liberty', 'Grand Canyon', 'Yellowstone', 'Golden Gate Bridge', 'Times Square'],
    foodRecommendations: ['Burger', 'BBQ Ribs', 'New York Pizza', 'Apple Pie', 'Clam Chowder'],
    localTransport: ['Domestic Flight', 'Amtrak Train', 'Greyhound Bus', 'Rental Car', 'Subway'],
    emergencyNumbers: { police: '911', ambulance: '911', fire: '911' },
    weather: { condition: 'Partly Cloudy', temp: 20, high: 26, low: 14 },
  },
  {
    id: 'thailand',
    name: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    capital: 'Bangkok',
    currency: 'THB (฿)',
    language: 'Thai',
    timezone: 'ICT (UTC+7)',
    safetyScore: 70,
    bestMonths: 'Nov – Feb',
    estimatedBudget: 55,
    image: 'https://images.pexels.com/photos/1659437/pexels-photo-1659437.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 15.87, lng: 100.9925 },
    attractions: ['Grand Palace', 'Wat Pho', 'Phi Phi Islands', 'Chiang Mai Old City', 'Ayutthaya'],
    foodRecommendations: ['Pad Thai', 'Tom Yum Goong', 'Som Tum', 'Green Curry', 'Mango Sticky Rice'],
    localTransport: ['BTS Skytrain', 'Tuk-Tuk', 'Songthaew', 'Ferry', 'Taxi'],
    emergencyNumbers: { police: '191', ambulance: '1669', fire: '199' },
    weather: { condition: 'Sunny', temp: 32, high: 35, low: 26 },
  },
  {
    id: 'italy',
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    capital: 'Rome',
    currency: 'EUR (€)',
    language: 'Italian',
    timezone: 'CET (UTC+1)',
    safetyScore: 74,
    bestMonths: 'Apr – Jun, Sep – Oct',
    estimatedBudget: 150,
    image: 'https://images.pexels.com/photos/2225442/pexels-photo-2225442.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 41.8719, lng: 12.5674 },
    attractions: ['Colosseum', 'Vatican City', 'Florence Duomo', 'Venice Canals', 'Amalfi Coast'],
    foodRecommendations: ['Pizza Napoletana', 'Pasta Carbonara', 'Gelato', 'Tiramisu', 'Risotto'],
    localTransport: ['Trenitalia', 'Italo Train', 'Bus', 'Vaporetto', 'Taxi'],
    emergencyNumbers: { police: '112', ambulance: '118', fire: '115' },
    weather: { condition: 'Sunny', temp: 24, high: 28, low: 18 },
  },
  {
    id: 'australia',
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    capital: 'Canberra',
    currency: 'AUD (A$)',
    language: 'English',
    timezone: 'AEST (UTC+10)',
    safetyScore: 87,
    bestMonths: 'Sep – Nov, Mar – May',
    estimatedBudget: 200,
    image: 'https://images.pexels.com/photos/995764/pexels-photo-995764.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: -25.2744, lng: 133.7751 },
    attractions: ['Sydney Opera House', 'Great Barrier Reef', 'Uluru', 'Bondi Beach', 'Twelve Apostles'],
    foodRecommendations: ['Meat Pie', 'Kangaroo Steak', 'Vegemite Toast', 'Pavlova', 'Barramundi'],
    localTransport: ['Domestic Flight', 'Train', 'Bus', 'Rental Car', 'Ferry'],
    emergencyNumbers: { police: '000', ambulance: '000', fire: '000' },
    weather: { condition: 'Sunny', temp: 22, high: 26, low: 15 },
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    capital: 'London',
    currency: 'GBP (£)',
    language: 'English',
    timezone: 'GMT (UTC+0)',
    safetyScore: 82,
    bestMonths: 'May – Sep',
    estimatedBudget: 190,
    image: 'https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg?auto=compress&cs=tinysrgb&w=1200',
    coordinates: { lat: 55.3781, lng: -3.436 },
    attractions: ['Big Ben', 'Tower of London', 'Stonehenge', 'Edinburgh Castle', 'Lake District'],
    foodRecommendations: ['Fish & Chips', 'Full English Breakfast', 'Afternoon Tea', 'Shepherd\'s Pie', 'Sticky Toffee Pudding'],
    localTransport: ['Tube', 'National Rail', 'Bus', 'Black Cab', 'Boris Bike'],
    emergencyNumbers: { police: '999', ambulance: '999', fire: '999' },
    weather: { condition: 'Cloudy', temp: 15, high: 18, low: 10 },
  },
];

export const VISA_INFO: VisaInfo[] = [
  {
    id: 'france',
    country: 'France',
    code: 'FR',
    flag: '🇫🇷',
    visaRequired: false,
    visaType: 'Schengen Visa (90 days max for non-EU)',
    passportValidity: '3 months beyond stay',
    vaccinations: ['Routine vaccines', 'Hepatitis A (recommended)'],
    travelAdvisory: 'Exercise normal precautions. Demonstrations may occur in major cities.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '17', ambulance: '15', fire: '18' },
    currency: 'EUR (€)',
    plugType: 'Type C/E (230V, 50Hz)',
    voltage: '230V',
    timezone: 'CET (UTC+1)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 85 Mbps)',
  },
  {
    id: 'japan',
    country: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    visaRequired: false,
    visaType: 'Temporary Visitor Visa (90 days)',
    passportValidity: 'Valid for entire stay',
    vaccinations: ['Routine vaccines', 'Japanese Encephalitis (rural areas)'],
    travelAdvisory: 'Exercise normal precautions. Earthquake-prone region.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '110', ambulance: '119', fire: '119' },
    currency: 'JPY (¥)',
    plugType: 'Type A/B (100V, 50/60Hz)',
    voltage: '100V',
    timezone: 'JST (UTC+9)',
    internetAvailable: true,
    internetSpeed: 'Very Fast (avg 120 Mbps)',
  },
  {
    id: 'indonesia',
    country: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    visaRequired: true,
    visaType: 'Visa on Arrival (30 days, $35)',
    passportValidity: '6 months beyond arrival',
    vaccinations: ['Hepatitis A', 'Typhoid', 'Yellow Fever (if from endemic area)'],
    travelAdvisory: 'Exercise increased caution due to terrorism and natural disasters.',
    advisoryLevel: 'moderate',
    emergencyContacts: { police: '110', ambulance: '118', fire: '113' },
    currency: 'IDR (Rp)',
    plugType: 'Type C/F (230V, 50Hz)',
    voltage: '230V',
    timezone: 'WIB (UTC+7)',
    internetAvailable: true,
    internetSpeed: 'Moderate (avg 25 Mbps)',
  },
  {
    id: 'uae',
    country: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    visaRequired: true,
    visaType: 'Tourist Visa (30-90 days, e-visa available)',
    passportValidity: '6 months beyond arrival',
    vaccinations: ['Routine vaccines', 'COVID-19 (check current requirements)'],
    travelAdvisory: 'Exercise normal precautions. Strict laws — familiarize before travel.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '999', ambulance: '998', fire: '997' },
    currency: 'AED (د.إ)',
    plugType: 'Type G (220V, 50Hz)',
    voltage: '220V',
    timezone: 'GST (UTC+4)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 90 Mbps)',
  },
  {
    id: 'switzerland',
    country: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    visaRequired: false,
    visaType: 'Schengen Visa (90 days max for non-EU)',
    passportValidity: '3 months beyond stay',
    vaccinations: ['Routine vaccines'],
    travelAdvisory: 'Exercise normal precautions. Avalanche risk in mountain areas in winter.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '117', ambulance: '144', fire: '118' },
    currency: 'CHF (Fr)',
    plugType: 'Type J (230V, 50Hz)',
    voltage: '230V',
    timezone: 'CET (UTC+1)',
    internetAvailable: true,
    internetSpeed: 'Very Fast (avg 110 Mbps)',
  },
  {
    id: 'usa',
    country: 'United States',
    code: 'US',
    flag: '🇺🇸',
    visaRequired: true,
    visaType: 'ESTA (90 days, visa waiver) or B-1/B-2 Visa',
    passportValidity: 'Valid for entire stay',
    vaccinations: ['Routine vaccines', 'COVID-19 (check current requirements)'],
    travelAdvisory: 'Exercise normal precautions. Gun violence risk varies by area.',
    advisoryLevel: 'moderate',
    emergencyContacts: { police: '911', ambulance: '911', fire: '911' },
    currency: 'USD ($)',
    plugType: 'Type A/B (120V, 60Hz)',
    voltage: '120V',
    timezone: 'Multiple (EST to PST)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 70 Mbps)',
  },
  {
    id: 'thailand',
    country: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    visaRequired: false,
    visaType: 'Visa Exemption (30-60 days depending on nationality)',
    passportValidity: '6 months beyond arrival',
    vaccinations: ['Hepatitis A', 'Typhoid', 'Japanese Encephalitis (rural)'],
    travelAdvisory: 'Exercise increased caution in southern border provinces.',
    advisoryLevel: 'moderate',
    emergencyContacts: { police: '191', ambulance: '1669', fire: '199' },
    currency: 'THB (฿)',
    plugType: 'Type A/B/C (220V, 50Hz)',
    voltage: '220V',
    timezone: 'ICT (UTC+7)',
    internetAvailable: true,
    internetSpeed: 'Moderate (avg 30 Mbps)',
  },
  {
    id: 'italy',
    country: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    visaRequired: false,
    visaType: 'Schengen Visa (90 days max for non-EU)',
    passportValidity: '3 months beyond stay',
    vaccinations: ['Routine vaccines', 'Hepatitis A (recommended)'],
    travelAdvisory: 'Exercise normal precautions. Petty crime in tourist areas.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '112', ambulance: '118', fire: '115' },
    currency: 'EUR (€)',
    plugType: 'Type C/F/L (230V, 50Hz)',
    voltage: '230V',
    timezone: 'CET (UTC+1)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 65 Mbps)',
  },
  {
    id: 'australia',
    country: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    visaRequired: true,
    visaType: 'ETA / eVisitor (90 days)',
    passportValidity: 'Valid for entire stay',
    vaccinations: ['Routine vaccines', 'COVID-19 (check current requirements)'],
    travelAdvisory: 'Exercise normal precautions. Bushfire risk in summer months.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '000', ambulance: '000', fire: '000' },
    currency: 'AUD (A$)',
    plugType: 'Type I (230V, 50Hz)',
    voltage: '230V',
    timezone: 'AEST (UTC+10)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 60 Mbps)',
  },
  {
    id: 'uk',
    country: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    visaRequired: false,
    visaType: 'Standard Visitor Visa (6 months)',
    passportValidity: 'Valid for entire stay',
    vaccinations: ['Routine vaccines'],
    travelAdvisory: 'Exercise normal precautions. Terrorist attacks are a risk.',
    advisoryLevel: 'low',
    emergencyContacts: { police: '999', ambulance: '999', fire: '999' },
    currency: 'GBP (£)',
    plugType: 'Type G (230V, 50Hz)',
    voltage: '230V',
    timezone: 'GMT (UTC+0)',
    internetAvailable: true,
    internetSpeed: 'Fast (avg 75 Mbps)',
  },
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'What\'s your ideal morning on vacation?',
    options: [
      { label: 'Exploring ancient ruins', value: 'cultural', icon: 'building' },
      { label: 'Hiking at dawn', value: 'adventure', icon: 'mountain' },
      { label: 'Room service breakfast', value: 'luxury', icon: 'hotel' },
      { label: 'Beach yoga', value: 'relaxation', icon: 'waves' },
    ],
  },
  {
    id: 'q2',
    question: 'How do you prefer to get around?',
    options: [
      { label: 'Luxury private car', value: 'luxury', icon: 'car' },
      { label: 'Local trains and buses', value: 'budget', icon: 'train' },
      { label: 'On foot or bicycle', value: 'adventure', icon: 'compass' },
      { label: 'Boat or ferry', value: 'relaxation', icon: 'waves' },
    ],
  },
  {
    id: 'q3',
    question: 'What\'s your food philosophy when traveling?',
    options: [
      { label: 'Michelin-star restaurants', value: 'luxury', icon: 'utensils' },
      { label: 'Street food all the way', value: 'budget', icon: 'utensils' },
      { label: 'Cooking classes with locals', value: 'cultural', icon: 'utensils' },
      { label: 'Resort buffet', value: 'family', icon: 'utensils' },
    ],
  },
  {
    id: 'q4',
    question: 'Pick your dream accommodation:',
    options: [
      { label: '5-star beachfront resort', value: 'luxury', icon: 'hotel' },
      { label: 'Boutique eco-lodge', value: 'adventure', icon: 'mountain' },
      { label: 'Historic city hotel', value: 'cultural', icon: 'building' },
      { label: 'Family-friendly villa', value: 'family', icon: 'home' },
    ],
  },
  {
    id: 'q5',
    question: 'What\'s your budget style?',
    options: [
      { label: 'Money is no object', value: 'luxury', icon: 'dollar' },
      { label: 'Stretch every dollar', value: 'budget', icon: 'dollar' },
      { label: 'Splurge on experiences', value: 'adventure', icon: 'dollar' },
      { label: 'Comfortable mid-range', value: 'family', icon: 'dollar' },
    ],
  },
  {
    id: 'q6',
    question: 'Which activity excites you most?',
    options: [
      { label: 'Museum hopping', value: 'cultural', icon: 'building' },
      { label: 'Scuba diving', value: 'adventure', icon: 'waves' },
      { label: 'Spa day', value: 'relaxation', icon: 'heart' },
      { label: 'Theme park', value: 'family', icon: 'ticket' },
    ],
  },
  {
    id: 'q7',
    question: 'Your ideal trip duration?',
    options: [
      { label: 'Weekend getaway', value: 'budget', icon: 'clock' },
      { label: '1-2 weeks', value: 'cultural', icon: 'clock' },
      { label: 'Month-long expedition', value: 'adventure', icon: 'clock' },
      { label: '2-week resort stay', value: 'relaxation', icon: 'clock' },
    ],
  },
  {
    id: 'q8',
    question: 'What climate do you prefer?',
    options: [
      { label: 'Tropical beaches', value: 'relaxation', icon: 'sun' },
      { label: 'Snowy mountains', value: 'adventure', icon: 'cloud-snow' },
      { label: 'Mild European spring', value: 'cultural', icon: 'cloud' },
      { label: 'Desert warmth', value: 'luxury', icon: 'sun' },
    ],
  },
  {
    id: 'q9',
    question: 'Who do you travel with?',
    options: [
      { label: 'Solo — just me', value: 'adventure', icon: 'user' },
      { label: 'Romantic partner', value: 'luxury', icon: 'heart' },
      { label: 'Kids and family', value: 'family', icon: 'users' },
      { label: 'Group of friends', value: 'budget', icon: 'users' },
    ],
  },
  {
    id: 'q10',
    question: 'What souvenirs do you bring home?',
    options: [
      { label: 'Local art and crafts', value: 'cultural', icon: 'palette' },
      { label: 'Designer brands', value: 'luxury', icon: 'shopping-bag' },
      { label: 'Photos and memories', value: 'budget', icon: 'camera' },
      { label: 'Spices and food', value: 'family', icon: 'utensils' },
    ],
  },
  {
    id: 'q11',
    question: 'How do you plan your trips?',
    options: [
      { label: 'Every minute scheduled', value: 'cultural', icon: 'calendar' },
      { label: 'Wing it completely', value: 'adventure', icon: 'compass' },
      { label: 'Concierge handles it', value: 'luxury', icon: 'sparkles' },
      { label: 'Flexible with must-dos', value: 'family', icon: 'calendar' },
    ],
  },
  {
    id: 'q12',
    question: 'What\'s your travel mantra?',
    options: [
      { label: 'Collect moments, not things', value: 'adventure', icon: 'camera' },
      { label: 'Luxury is the destination', value: 'luxury', icon: 'crown' },
      { label: 'Travel to learn', value: 'cultural', icon: 'book-open' },
      { label: 'Relax and recharge', value: 'relaxation', icon: 'heart' },
    ],
  },
];

export const EMERGENCY_PHRASES: EmergencyPhrase[] = [
  {
    phrase: 'Help! I need assistance.',
    translations: [
      { language: 'French', translation: 'Au secours! J\'ai besoin d\'aide.' },
      { language: 'Japanese', translation: '助けてください！' },
      { language: 'Spanish', translation: '¡Ayuda! Necesito asistencia.' },
      { language: 'Thai', translation: 'ช่วยด้วย! ฉันต้องการความช่วยเหลือ' },
    ],
  },
  {
    phrase: 'Where is the nearest hospital?',
    translations: [
      { language: 'French', translation: 'Où est l\'hôpital le plus proche?' },
      { language: 'Japanese', translation: '最寄りの病院はどこですか？' },
      { language: 'Spanish', translation: '¿Dónde está el hospital más cercano?' },
      { language: 'Thai', translation: 'โรงพยาบาลที่ใกล้ที่สุดอยู่ที่ไหน?' },
    ],
  },
  {
    phrase: 'Please call the police.',
    translations: [
      { language: 'French', translation: 'Veuillez appeler la police.' },
      { language: 'Japanese', translation: '警察を呼んでください。' },
      { language: 'Spanish', translation: 'Por favor llame a la policía.' },
      { language: 'Thai', translation: 'โปรดโทรเรียกตำรวจ' },
    ],
  },
  {
    phrase: 'I need a doctor.',
    translations: [
      { language: 'French', translation: 'J\'ai besoin d\'un médecin.' },
      { language: 'Japanese', translation: '医者が必要です。' },
      { language: 'Spanish', translation: 'Necesito un médico.' },
      { language: 'Thai', translation: 'ฉันต้องการหมอ' },
    ],
  },
  {
    phrase: 'Can you help me find my hotel?',
    translations: [
      { language: 'French', translation: 'Pouvez-vous m\'aider à trouver mon hôtel?' },
      { language: 'Japanese', translation: 'ホテルを探すのを手伝ってもらえますか？' },
      { language: 'Spanish', translation: '¿Puede ayudarme a encontrar mi hotel?' },
      { language: 'Thai', translation: 'คุณช่วยหาโรงแรมของฉันได้ไหม?' },
    ],
  },
  {
    phrase: 'I lost my passport.',
    translations: [
      { language: 'French', translation: 'J\'ai perdu mon passeport.' },
      { language: 'Japanese', translation: 'パスポートをなくしました。' },
      { language: 'Spanish', translation: 'Perdí mi pasaporte.' },
      { language: 'Thai', translation: 'ฉันทำพาสปอร์ตหาย' },
    ],
  },
  {
    phrase: 'How much does this cost?',
    translations: [
      { language: 'French', translation: 'Combien ça coûte?' },
      { language: 'Japanese', translation: 'これはいくらですか？' },
      { language: 'Spanish', translation: '¿Cuánto cuesta?' },
      { language: 'Thai', translation: 'นี่ราคาเท่าไหร่?' },
    ],
  },
  {
    phrase: 'Where is the embassy?',
    translations: [
      { language: 'French', translation: 'Où est l\'ambassade?' },
      { language: 'Japanese', translation: '大使館はどこですか？' },
      { language: 'Spanish', translation: '¿Dónde está la embajada?' },
      { language: 'Thai', translation: 'สถานทูตอยู่ที่ไหน?' },
    ],
  },
];

export const CURRENCY_RATES: CurrencyRate[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', rate: 1 },
  { code: 'EUR', name: 'Euro', symbol: '€', rate: 0.92 },
  { code: 'GBP', name: 'British Pound', symbol: '£', rate: 0.79 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 149.5 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', rate: 0.88 },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', rate: 3.67 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 15580 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 35.2 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 1.52 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rate: 1.36 },
];

export const UNIT_CONVERSIONS: UnitConversion[] = [
  {
    category: 'Temperature',
    units: [
      { name: 'Celsius', factor: 1, symbol: '°C' },
      { name: 'Fahrenheit', factor: 1, symbol: '°F' },
    ],
  },
  {
    category: 'Distance',
    units: [
      { name: 'Kilometers', factor: 1, symbol: 'km' },
      { name: 'Miles', factor: 0.621371, symbol: 'mi' },
      { name: 'Meters', factor: 1000, symbol: 'm' },
      { name: 'Feet', factor: 3280.84, symbol: 'ft' },
    ],
  },
  {
    category: 'Weight',
    units: [
      { name: 'Kilograms', factor: 1, symbol: 'kg' },
      { name: 'Pounds', factor: 2.20462, symbol: 'lb' },
      { name: 'Grams', factor: 1000, symbol: 'g' },
      { name: 'Ounces', factor: 35.274, symbol: 'oz' },
    ],
  },
  {
    category: 'Volume',
    units: [
      { name: 'Liters', factor: 1, symbol: 'L' },
      { name: 'Gallons', factor: 0.264172, symbol: 'gal' },
      { name: 'Milliliters', factor: 1000, symbol: 'mL' },
    ],
  },
];

export const SHARE_OPTIONS: ShareOption[] = [
  { platform: 'whatsapp', label: 'WhatsApp', icon: 'message-circle', color: '#25D366' },
  { platform: 'email', label: 'Email', icon: 'mail', color: '#EA4335' },
  { platform: 'twitter', label: 'X (Twitter)', icon: 'twitter', color: '#1DA1F2' },
  { platform: 'linkedin', label: 'LinkedIn', icon: 'linkedin', color: '#0077B5' },
  { platform: 'copy', label: 'Copy Link', icon: 'link', color: '#6366F1' },
];

export const WORLD_TIMEZONES = [
  { city: 'New York', tz: 'America/New_York', offset: -5 },
  { city: 'London', tz: 'Europe/London', offset: 0 },
  { city: 'Paris', tz: 'Europe/Paris', offset: 1 },
  { city: 'Dubai', tz: 'Asia/Dubai', offset: 4 },
  { city: 'Tokyo', tz: 'Asia/Tokyo', offset: 9 },
  { city: 'Sydney', tz: 'Australia/Sydney', offset: 11 },
  { city: 'Bangkok', tz: 'Asia/Bangkok', offset: 7 },
  { city: 'Los Angeles', tz: 'America/Los_Angeles', offset: -8 },
];

export const EXPENSE_CATEGORIES: { value: Expense['category']; label: string; icon: LucideIcon; color: string }[] = [
  { value: 'flights', label: 'Flights', icon: Plane, color: '#3b82f6' },
  { value: 'hotels', label: 'Hotels', icon: Hotel, color: '#8b5cf6' },
  { value: 'food', label: 'Food', icon: Utensils, color: '#f59e0b' },
  { value: 'transport', label: 'Transport', icon: Car, color: '#06b6d4' },
  { value: 'shopping', label: 'Shopping', icon: ShoppingBag, color: '#ec4899' },
  { value: 'activities', label: 'Activities', icon: Ticket, color: '#10b981' },
  { value: 'other', label: 'Other', icon: Package, color: '#64748b' },
];


export const COMPARISON_METRICS: { label: string; icon: string; key: string }[] = [
  { label: 'Weather', icon: 'sun', key: 'weather' },
  { label: 'Budget', icon: 'wallet', key: 'budget' },
  { label: 'Food', icon: 'utensils', key: 'food' },
  { label: 'Nightlife', icon: 'moon', key: 'nightlife' },
  { label: 'Safety', icon: 'shield', key: 'safety' },
  { label: 'Internet', icon: 'wifi', key: 'internet' },
  { label: 'Transport', icon: 'car', key: 'transport' },
  { label: 'Attractions', icon: 'map-pin', key: 'attractions' },
  { label: 'Adventure', icon: 'mountain', key: 'adventure' },
  { label: 'Family', icon: 'users', key: 'family' },
];

export const DESTINATION_COMPARISON_DATA: Record<string, Record<string, number>> = {
  paris: { weather: 8, budget: 4, food: 9, nightlife: 8, safety: 8, internet: 9, transport: 9, attractions: 10, adventure: 5, family: 7 },
  tokyo: { weather: 7, budget: 5, food: 10, nightlife: 9, safety: 10, internet: 10, transport: 10, attractions: 9, adventure: 6, family: 8 },
  bali: { weather: 9, budget: 9, food: 8, nightlife: 7, safety: 6, internet: 5, transport: 4, attractions: 8, adventure: 9, family: 6 },
  dubai: { weather: 6, budget: 3, food: 7, nightlife: 8, safety: 9, internet: 9, transport: 8, attractions: 8, adventure: 7, family: 8 },
  switzerland: { weather: 7, budget: 2, food: 7, nightlife: 5, safety: 10, internet: 10, transport: 10, attractions: 9, adventure: 10, family: 8 },
  newyork: { weather: 7, budget: 2, food: 9, nightlife: 10, safety: 7, internet: 9, transport: 9, attractions: 10, adventure: 6, family: 7 },
};
